In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv('../Global/Global_Finance_Data.csv')

In [3]:
df = df.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)

In [4]:
df

,Date,Close,High,Low,Open,Volume,Company,Country
0,2025-01-02,38.309410,38.333379,37.858826,37.868412,4682324,BHP Group Ltd,Australia
1,2025-01-03,38.117672,38.386109,38.040978,38.203955,4364816,BHP Group Ltd,Australia
2,2025-01-06,37.369896,37.657503,37.216505,37.628744,8228960,BHP Group Ltd,Australia
3,2025-01-07,37.101460,37.389067,36.813852,37.369893,7135772,BHP Group Ltd,Australia
4,2025-01-08,37.772545,37.935521,37.120633,37.274024,8194023,BHP Group Ltd,Australia
...,...,...,...,...,...,...,...,...
57629,2026-02-19,77.000000,78.699997,76.589996,77.750000,30139200,Netflix Inc,USA
57630,2026-02-20,78.669998,78.849998,76.400002,76.610001,32411300,Netflix Inc,USA
57631,2026-02-23,76.019997,77.830002,75.010002,77.790001,38363000,Netflix Inc,USA
57632,2026-02-24,78.040001,78.120003,75.209999,75.730003,33079100,Netflix Inc,USA
57633,2026-02-25,82.699997,83.120003,79.250000,79.430000,69319300,Netflix Inc,USA

In [5]:
df.dtypes

Date        object
Close      float64
High       float64
Low        float64
Open       float64
Volume       int64
Company     object
Country     object
dtype: object

In [6]:
df.Date = df.Date.astype('datetime64[ns]')

In [7]:
df

,Date,Close,High,Low,Open,Volume,Company,Country
0,2025-01-02,38.309410,38.333379,37.858826,37.868412,4682324,BHP Group Ltd,Australia
1,2025-01-03,38.117672,38.386109,38.040978,38.203955,4364816,BHP Group Ltd,Australia
2,2025-01-06,37.369896,37.657503,37.216505,37.628744,8228960,BHP Group Ltd,Australia
3,2025-01-07,37.101460,37.389067,36.813852,37.369893,7135772,BHP Group Ltd,Australia
4,2025-01-08,37.772545,37.935521,37.120633,37.274024,8194023,BHP Group Ltd,Australia
...,...,...,...,...,...,...,...,...
57629,2026-02-19,77.000000,78.699997,76.589996,77.750000,30139200,Netflix Inc,USA
57630,2026-02-20,78.669998,78.849998,76.400002,76.610001,32411300,Netflix Inc,USA
57631,2026-02-23,76.019997,77.830002,75.010002,77.790001,38363000,Netflix Inc,USA
57632,2026-02-24,78.040001,78.120003,75.209999,75.730003,33079100,Netflix Inc,USA
57633,2026-02-25,82.699997,83.120003,79.250000,79.430000,69319300,Netflix Inc,USA